version: "2"
services:
  information-db:
    image: mongo
    command: mongod --port 3305
    ports:
      - "3305:3305"
  information-ms:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - information-db
